[project]
name = "arkplanner"
version = "1.1.4"
description = "ArkPlanner backend inside Penguin Statistics"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "numpy>=2.2.0",
    "sanic>=25.3.0",
    "scipy>=1.15.2",
]
